[package]
name = "libhello"
version = "0.1.0"
edition = "2024"

[lib]
name = "libhello"

[[bin]]
name = "side"
path = "src/bin/side.rs"

[build-dependencies]
cc = "1.0"  # To compile the C code
[dependencies]
rand = "0.9.0"